matrix:
  include:
    - os: osx
      osx_image: xcode11
      language: node_js
      node_js: "10"
    - os: linux
      services: docker
      language: generic
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
before_script:
  - REPORTER_OS_NAME=$([ "$TRAVIS_OS_NAME" = "linux" ] && echo "linux" || echo "darwin")
  - curl -L "https://codeclimate.com/downloads/test-reporter/test-reporter-latest-${REPORTER_OS_NAME}-amd64" > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - PUBLISH=$([ "$TRAVIS_TAG" != "" ] && echo "onTag" || echo "never")
  - NOTARIZE=$([ "$TRAVIS_TAG" != "" ] && echo "true" || echo "")
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        -e ELECTRON_CACHE=$HOME/.cache/electron \
        -e ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder \
        -e GH_TOKEN=$GH_TOKEN \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "\
          npm install && \
          npm run test && \
          npm run build -- -p ${PUBLISH} --linux --win
        "
    else
      npm run test && \
      npm run build -- -p ${PUBLISH} --mac
    fi
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
after_script:
  - sudo sed -i -e "s|^SF:/project|SF:$(pwd)|" coverage/lcov.info
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
